In [1]:
import pandas as pd

In [3]:
df_exams=pd.read_csv("sample_data/StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

**1. Math Operations**

***1.1 Operations in Columns***

In [4]:
#select a column and calculate the total sum
df_exams['math score'].sum()

np.int64(66089)

In [5]:
#Excel tasks we can do in pandas: count, max, min, std
df_exams['math score'].count()

np.int64(1000)

In [6]:
df_exams['math score'].mean()   #get the average value

np.float64(66.089)

In [7]:
df_exams['math score'].std()

15.163080096009468

In [8]:
df_exams['math score'].max()

100

In [9]:
df_exams['math score'].min()

0

In [10]:
#easier calculation with the .describe() method
df_exams.describe()     #gets all the int columns in our data

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

***1.2 Operations in rows***

In [11]:
#calculate the sum in a row
df_exams['math score']+ df_exams['reading score']+ df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [13]:
#calculate the average score and assign the result to a new column
df_exams['average score']=(df_exams['math score']+ df_exams['reading score']+ df_exams['writing score'] )/3

In [15]:
df_exams.round(2)   #control the number of decimals we want

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00