In [1]:
import pandas as pd

In [2]:
#load the csv file using pandas
df_exams=pd.read_csv("sample_data/StudentsPerformance.csv")

In [3]:
#print first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

**1 Adding a new Column**

***1.1 Adding a new column with a scalar value***

In [4]:
#adding new column to dataframe. Scalar value means all the rows are going to have the same value
df_exams['language score'] = 70

In [5]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

***1.2 Adding a new column with an array***

In [6]:
#we know the dataframe has 1000 row.
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [7]:
#we create an array with 1000 elements as the dataframe has an index upto 1000
import numpy as np

In [12]:
#create an array of 1000 elements
language_score=np.arange(0,1000)   #this are the limits of my dataframe i.e starting index and the last one

In [13]:
#verify the length
len(language_score)

1000

In [14]:
#add the new column to the dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [16]:
#Now lets give the marks to our new column using numpy and random
#between 1-100
int_language_score=np.random.randint(1, 100, size=1000)

In [17]:
#check the minimum value of the array
min(int_language_score)

np.int64(1)

In [18]:
#check the maximum value
max(int_language_score)

np.int64(99)

In [19]:
#add our new column to the dataframe
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,42
1,female,group C,some college,standard,completed,69,90,88,45
2,female,group B,master's degree,standard,none,90,95,93,82
3,male,group A,associate's degree,free/reduced,none,47,57,44,81
4,male,group C,some college,standard,none,76,78,75,1
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,73
996,male,group C,high school,free/reduced,none,62,55,55,93
997,female,group C,high school,free/reduced,completed,59,71,65,49
998,female,group D,some college,standard,completed,68,78,77,63
999,female,group D,some college,free/reduced,none,77,86,86,93

In [21]:
#lets create random float numbers between 32 and 38
stud_temp=np.random.uniform(32, 38, size=1000)

In [22]:
#lets add our new floating point column to the table
df_exams['Temperature°C'] = stud_temp
#display
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,Temperature°C
0,female,group B,bachelor's degree,standard,none,72,72,74,42,37.099347
1,female,group C,some college,standard,completed,69,90,88,45,37.957710
2,female,group B,master's degree,standard,none,90,95,93,82,33.685611
3,male,group A,associate's degree,free/reduced,none,47,57,44,81,32.581128
4,male,group C,some college,standard,none,76,78,75,1,35.475831
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,73,37.811486
996,male,group C,high school,free/reduced,none,62,55,55,93,37.014695
997,female,group C,high school,free/reduced,completed,59,71,65,49,33.046942
998,female,group D,some college,standard,completed,68,78,77,63,35.911158
999,female,group D,some college,free/reduced,none,77,86,86,93,36.741266