In [1]:
import pandas as pd

**1 Read a .csv from a URL with pandas**

Target URL:https://www.football-data.co.uk/data.php

In [3]:
#reading 1 csv file from the website
df_premier24=pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

In [4]:
#show dataframe
df_premier24

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [5]:
#rename columns
df_premier24.rename(columns={'FTHG':'home_goals',
                             'FTAG':'away_goals'}, inplace=True)

In [6]:
#show df
df_premier24

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

**2 Read .csv from Multiple URLs with Pandas**

***Link: root+season+league***
The links have a pattern:


*  https://www.football-data.co.uk/mmz4281/2425/E0.csv
*   https://www.football-data.co.uk/mmz4281/2425/E1.csv

In [7]:
#;ink structure
"https://www.football-data.co.uk/mmz4281/"+"2425"+"/"+"E1"+".csv"

'https://www.football-data.co.uk/mmz4281/2425/E1.csv'

In [9]:
#We are going to extract the csv files using a for loop
#create a root variable
root="https://www.football-data.co.uk/mmz4281/"

In [10]:
#create list of leagues
leagues=['E0', 'E1', 'E2', 'E3', 'EC']
frames=[]  #create an empty list to store the dataframe

#lets loop throught the list above
for league in leagues:
  df=pd.read_csv(root+"2425"+"/"+league+".csv")
  frames.append(df)     #now add each dataframe to our empty list

In [11]:
#length of frames
len(frames)   #we are supposed to get 5 elements in our list

5

In [12]:
#show 1st, 2nd and 3rd element
frames[0]  #the first element of our list

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [14]:
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,10/08/2024,15:00,Aldershot,Forest Green,3,3,D,2,1,...,1.83,1.98,1.87,1.99,1.87,2.00,1.83,1.99,1.88,2.02
1,EC,10/08/2024,15:00,Altrincham,Woking,1,0,H,1,0,...,1.83,1.98,1.83,2.04,1.85,2.04,1.82,1.95,1.86,2.14
2,EC,10/08/2024,15:00,Boston Utd,Rochdale,0,3,A,0,2,...,1.85,1.95,1.88,1.98,1.88,1.98,1.84,1.93,1.92,2.00
3,EC,10/08/2024,15:00,Dag and Red,Wealdstone,2,1,H,0,0,...,1.90,1.90,1.89,1.95,1.91,1.95,1.87,1.88,1.91,2.06
4,EC,10/08/2024,15:00,Fylde,Solihull,3,2,H,1,2,...,1.78,2.03,1.76,2.10,1.80,2.10,1.76,2.01,1.80,2.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,05/05/2025,15:00,Maidenhead,Boston Utd,3,0,H,1,0,...,1.80,2.00,1.80,2.07,1.81,2.07,1.77,2.02,1.83,2.13
548,EC,05/05/2025,15:00,Oldham,Ebbsfleet,2,0,H,1,0,...,1.85,1.95,1.88,1.98,1.90,1.98,1.87,1.91,1.94,1.90
549,EC,05/05/2025,15:00,Solihull,Dag and Red,1,1,D,0,1,...,1.98,1.83,1.96,1.89,1.98,1.89,1.95,1.84,2.02,1.91
550,EC,05/05/2025,15:00,Sutton,Woking,1,1,D,0,1,...,1.95,1.85,1.93,1.93,1.95,1.93,1.93,1.84,2.01,1.96
551,EC,05/05/2025,15:00,Wealdstone,Halifax,3,1,H,3,0,...,2.03,1.78,2.07,1.80,2.07,1.81,2.01,1.78,2.12,1.72

**2.2 Multiple Seasons**

In [18]:
for season in range(19, 25):
  print(str(season)+ str(season+1))

1920
2021
2122
2223
2324
2425

In [19]:
#loop through the range of seasons and insert new column
leagues=['E0', 'E2', 'E3']
frames=[]  #create an empty list to store the dataframe

#lets loop throught the list above
for league in leagues:
  for season in range(19, 25):
    df=pd.read_csv(root+str(season)+ str(season+1)+"/"+league+".csv")
    df.insert(1, 'Season',season)
    frames.append(df)     #now add each dataframe to our empty list

In [20]:
#total frames( 6 seasons x 4 leagues)
len(frames)

18

In [23]:
#show 1st and last element
frames[17]

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E3,24,09/08/2024,20:00,Chesterfield,Swindon,1,1,D,1,...,1.83,2.03,1.86,2.03,1.89,2.05,1.83,1.97,1.91,2.06
1,E3,24,10/08/2024,15:00,AFC Wimbledon,Colchester,4,2,H,3,...,1.75,2.05,1.83,2.07,1.83,2.17,1.76,2.05,1.86,2.12
2,E3,24,10/08/2024,15:00,Barrow,Crewe,1,0,H,1,...,1.88,1.98,1.87,2.02,1.90,2.04,1.84,1.95,1.88,2.09
3,E3,24,10/08/2024,15:00,Cheltenham,Newport County,3,2,H,2,...,1.93,1.93,1.96,1.93,1.98,1.96,1.91,1.88,2.05,1.92
4,E3,24,10/08/2024,15:00,Doncaster,Accrington,4,1,H,1,...,1.93,1.93,1.95,1.93,1.95,1.98,1.89,1.89,1.98,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,24,03/05/2025,15:00,Morecambe,Harrogate,1,2,A,1,...,1.78,2.10,1.74,2.12,1.78,2.18,1.73,2.09,1.81,2.22
548,E3,24,03/05/2025,15:00,Newport County,Tranmere,1,4,A,1,...,1.78,2.03,1.84,2.00,1.84,2.03,1.81,1.98,1.84,2.13
549,E3,24,03/05/2025,15:00,Notts County,Doncaster,1,2,A,0,...,1.80,2.05,1.79,2.06,1.81,2.12,1.76,2.05,1.85,2.15
550,E3,24,03/05/2025,15:00,Port Vale,Gillingham,0,1,A,0,...,2.03,1.83,2.04,1.81,2.05,1.83,2.00,1.80,2.09,1.86
551,E3,24,03/05/2025,15:00,Swindon,Milton Keynes Dons,0,0,D,0,...,2.03,1.83,1.99,1.85,2.04,1.86,1.98,1.83,2.11,1.86

**3 Organize All the Data in a Dictionary**

In [26]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1',
              'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1',
              'English Premier League':'E0',
              'English League 1':'E2',
              'English League 2':'E3',
             }

In [27]:
dict_countries['English League 1']

'E2'

In [29]:
#lets see what we get when we loop through a dictionary
for league in dict_countries:
  print(dict_countries[league])  #this allows us to get the values in a dictionary

SP1
SP2
D1
E0
E2
E3

In [30]:
dict_historical_data={}

#loop through the range of seasons and insert new column
#leagues=['E0', 'E2', 'E3']
 #create an empty list to store the dataframe

#lets loop throught the list above
for league in dict_countries:
  frames=[] #prevents accumilation of the previous data and emptys the list with each iteration

  for season in range(19, 25):
    df=pd.read_csv(root+str(season)+ str(season+1)+"/"+dict_countries[league]+".csv")
    df.insert(1, 'Season',season)
    frames.append(df)     #now add each dataframe to our empty list

  df_concat=pd.concat(frames)
  dict_historical_data[league]=df_concat  #assign name of league and its dataframe

In [33]:
#show dataframe inside dict_historical_data
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])

In [34]:
dict_historical_data['English Premier League']

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
0,E0,19,09/08/2019,20:00,Liverpool,Norwich,4,1,H,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,19,10/08/2019,12:30,West Ham,Man City,0,5,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,19,10/08/2019,15:00,Bournemouth,Sheffield United,1,1,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,19,10/08/2019,15:00,Burnley,Southampton,3,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,19,10/08/2019,15:00,Crystal Palace,Everton,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,...,1.30,6.11,10.20,1.27,7.0,13.00,1.50,2.94,1.93,2.05
376,E0,24,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,...,3.50,3.86,2.06,3.55,3.9,2.14,1.76,2.28,1.86,2.14
377,E0,24,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,...,12.20,6.11,1.28,13.00,6.8,1.28,1.45,3.15,2.06,1.89
378,E0,24,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,...,3.63,4.12,1.95,3.95,4.2,1.93,1.51,2.92,2.06,1.93
379,E0,24,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,...,2.98,3.80,2.31,3.05,3.8,2.42,1.54,2.78,1.89,2.10